sprint-2/step-1 сдача работы
chaccess/react-burger pull request #1
Opened 2024-07-05 09:59 UTC by chaccess

2024-07-06 06:15 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Есть модальные окна;
- Данные получают с сервера;

### **Но есть несколько замечаний, которые нужно исправить:**

- Отметил замечания в коде;

2024-07-06 06:15 UTC, ArslanMustafin commented on src/components/Burger-Ingredients/Burger-Ingredients.tsx
> +  }, [scrollPaneExists]);
**Надо исправить:**

Лучше объединить всё в 1 `useEffect`

```js
  useEffect(() => {
    const scrollPaneElement =
      scrollPane.current !== null ? (scrollPane.current as HTMLElement) : null;

    if (!scrollPaneElement) return;

    scrollPaneElement.addEventListener('scroll', highLightTab);

    return () => {
      scrollPaneElement.removeEventListener('scroll', highLightTab);
    };
  }, []);
```

2024-07-06 06:15 UTC, ArslanMustafin commented on src/components/Burger-Ingredients/Burger-Ingredients.tsx
> +          ].map(({ value, title }) => (
**Можно лучше:**

лучше вынести массив в отдельную константу.

2024-07-06 06:15 UTC, ArslanMustafin commented on src/components/Burger-Ingredients/Burger-Ingredients.tsx
> +          <IngredientDetails {...ingredientInModal} />
**Можно лучше:**

Раз здесь у вас используется редакс, то лучше использовать уже его, а не пропсы.

2024-07-06 06:15 UTC, ArslanMustafin commented on src/components/Modal-Overlay/Modal-Overlay.tsx
> +};
**Надо исправить:**

Компонент `ModalOverlay` это просто подложка, он не должен создаваться через портал.

```js
import styles from "./modal-overlay.module.css";

export const ModalOverlay = ({ onClick }) => {
  return <div className={styles.overlay} onClick={onClick} />;
};
```

2024-07-06 06:15 UTC, ArslanMustafin commented on src/components/Modal/Modal.tsx
> +  }
**Надо исправить:**

Высчитывать позицию для модального окна лучше через `css`. 

```css
.modal {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 3;
  width: 640px;
  margin: auto;
  padding: 40px 40px 60px;
  background-color: #1c1c21;
  border-radius: 40px;
  box-shadow: 0px 24px 32px rgba(0, 0, 0, 0.04),
    0px 16px 24px rgba(0, 0, 0, 0.04), 0px 4px 8px rgba(0, 0, 0, 0.04),
    0px 0px 1px rgba(0, 0, 0, 0.04);
}
```

2024-07-07 17:35 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

2024-07-07 22:28 UTC, merged

2024-07-10 22:53 UTC, mikebars1995 reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

К сожалению, работу придется отклонить без потери итерации, так как нет открытого пулл реквеста, скрин https://disk.yandex.ru/i/U3XDA15XqLScQg

2024-07-16 17:08 UTC, chaccess commented
@mikebars1995 у меня уже все проверили и приняли
просто я сдал не во второй спринт, а в первый, потому что у меня был залочен урок по второму спринту в практикуме